In [1]:
# Importación de librerías principales
import pandas as pd
import numpy as np

In [2]:
# Cargar el dataset

df_clientes = pd.read_csv('Raw/clientes.csv')

# Mostrar las primeras 5 filas para entender la estructura
display(df_clientes.head())

   id_cliente nombre_cliente provincia   segmento  fecha_alta
0        2001    Cliente 001   Rosario    Premium  2022-04-14
1        2002    Cliente 002   Mendoza  Mayorista  2023-05-01
2        2003    Cliente 003   Tucumán  Mayorista  2022-01-14
3        2004    Cliente 004   Tucumán     Básico  2022-12-10
4        2005    Cliente 005      CABA    Premium  2023-01-20

In [3]:
# Información general: cantidad de filas, columnas, tipos de datos y valores no nulos
print("--- Información General del Dataset ---")
df_clientes.info()

print(f"\nDimensiones totales: {df_clientes.shape[0]} filas y {df_clientes.shape[1]} columnas.")

--- Información General del Dataset ---
<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      80 non-null     int64
 1   nombre_cliente  80 non-null     str
 2   provincia       80 non-null     str
 3   segmento        80 non-null     str
 4   fecha_alta      80 non-null     str
dtypes: int64(1), str(4)
memory usage: 3.3 KB

Dimensiones totales: 80 filas y 5 columnas.

In [4]:
# 1. Convertir la fecha a formato datetime
df_clientes['fecha_alta'] = pd.to_datetime(df_clientes['fecha_alta'])

df_clientes['fecha_alta'] = pd.to_datetime(
    df_clientes['fecha_alta'],
    format='mixed',
    dayfirst=True
)

# 2. Convertir el ID a string (object) porque es un identificador, no un número para operar
df_clientes['id_cliente'] = df_clientes['id_cliente'].astype(str)

# 3. Convertir a tipo 'category' las variables que tienen pocos valores únicos (ahorra memoria y agiliza cruces)
df_clientes['provincia'] = df_clientes['provincia'].astype('category')
df_clientes['segmento'] = df_clientes['segmento'].astype('category')

# Verificamos que los cambios se hayan aplicado
print("--- Nuevos Tipos de Datos ---")
display(df_clientes.dtypes)

--- Nuevos Tipos de Datos ---

id_cliente                   str
nombre_cliente               str
provincia               category
segmento                category
fecha_alta        datetime64[us]
dtype: object

In [5]:
# Chequeo de valores nulos
print("--- Conteo de Valores Nulos ---")
display(df_clientes.isnull().sum())

# Chequeo de duplicados totales y por ID
duplicados_totales = df_clientes.duplicated().sum()
ids_duplicados = df_clientes.duplicated(subset=['id_cliente']).sum()

print("\n--- Análisis de Duplicados ---")
print(f"Filas exactamente duplicadas en todas las columnas: {duplicados_totales}")
print(f"IDs de cliente repetidos: {ids_duplicados}")

# Si hubiera IDs duplicados, podríamos verlos con:
# display(df_clientes[df_clientes.duplicated(subset=['id_cliente'], keep=False)].sort_values('id_cliente'))

--- Conteo de Valores Nulos ---

id_cliente        0
nombre_cliente    0
provincia         0
segmento          0
fecha_alta        0
dtype: int64

--- Análisis de Duplicados ---
Filas exactamente duplicadas en todas las columnas: 0
IDs de cliente repetidos: 0

In [6]:
# Resumen descriptivo para variables categóricas y fechas
print("--- Resumen Estadístico (Categóricas y Fechas) ---")
display(df_clientes.describe(include=['category', 'object', 'datetime64']))

--- Resumen Estadístico (Categóricas y Fechas) ---

C:\Users\franc\AppData\Local\Temp\ipykernel_25824\3184912834.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df_clientes.describe(include=['category', 'object', 'datetime64']))

       id_cliente nombre_cliente     provincia segmento           fecha_alta
count          80             80            80       80                   80
unique         80             80             7        4                  NaN
top          2001    Cliente 001  Buenos Aires   Básico                  NaN
freq            1              1            16       28                  NaN
mean          NaN            NaN           NaN      NaN  2023-01-11 04:12:00
min           NaN            NaN           NaN      NaN  2022-01-03 00:00:00
25%           NaN            NaN           NaN      NaN  2022-06-02 06:00:00
50%           NaN            NaN           NaN      NaN  2023-01-18 12:00:00
75%           NaN            NaN           NaN      NaN  2023-06-26 00:00:00
max           NaN            NaN           NaN      NaN  2024-03-11 00:00:00

In [7]:
df_clientes

   id_cliente nombre_cliente     provincia   segmento fecha_alta
0        2001    Cliente 001       Rosario    Premium 2022-04-14
1        2002    Cliente 002       Mendoza  Mayorista 2023-05-01
2        2003    Cliente 003       Tucumán  Mayorista 2022-01-14
3        2004    Cliente 004       Tucumán     Básico 2022-12-10
4        2005    Cliente 005          CABA    Premium 2023-01-20
..        ...            ...           ...        ...        ...
75       2076    Cliente 076       Mendoza    Premium 2023-06-02
76       2077    Cliente 077       Rosario    Premium 2023-11-25
77       2078    Cliente 078          CABA   Estándar 2022-04-14
78       2079    Cliente 079  Buenos Aires  Mayorista 2024-01-03
79       2080    Cliente 080      Santa Fe     Básico 2024-01-20

[80 rows x 5 columns]

In [9]:
display(df_clientes.dtypes)

id_cliente                   str
nombre_cliente               str
provincia               category
segmento                category
fecha_alta        datetime64[us]
dtype: object

In [10]:
import os

# 1. Crear la carpeta 'Processed' si no existe
os.makedirs('Processed', exist_ok=True)

# 2. Exportar el DataFrame de Clientes
# Usamos index=False para que Pandas no agregue una columna extra con los números de fila
df_clientes.to_csv('Processed/clientes_procesado.csv', index=False, encoding='utf-8')

print("✅ df_clientes exportado exitosamente a Processed/clientes_procesado.csv")

✅ df_clientes exportado exitosamente a Processed/clientes_procesado.csv